// web/src/lib/components/ItemCard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Item } from '$lib/stores/items';
  import { userId } from '$lib/stores/user';
  import { getDb } from '$lib/db';
  import { itemLikes, sources } from '$lib/schema';
  import { eq, and } from 'drizzle-orm';
  import { logger } from '$lib/utils/logger';

  export let item: Item;

  let liked: number | null = null;
  let sourceName = 'Unknown';
  let loading = false;
  let currentUserId: string = '';

  onMount(async () => {
    try {
      // Subscribe to user ID
      userId.subscribe(id => {
        currentUserId = id;
      })();

      const db = await getDb();
      // Get the user like status
      const result = await db
        .select()
        .from(itemLikes)
        .where(and(
          eq(itemLikes.itemId, item.id),
          eq(itemLikes.userId, currentUserId)
        ))
        .limit(1);

      if (result.length > 0) {
        liked = result[0].score;
      }

      // Get source name
      const sourceResult = await db
        .select()
        .from(sources)
        .where(eq(sources.id, item.sourceId))
        .limit(1);

      if (sourceResult.length > 0) {
        sourceName = sourceResult[0].name;
      }
    } catch (err) {
      logger.error('Failed to load like status:', err);
    }
  });

  async function toggleLike(score: number) {
    if (loading) return;
    loading = true;

    try {
      const db = await getDb();

      // Check if like exists
      const existing = await db
        .select()
        .from(itemLikes)
        .where(and(
          eq(itemLikes.itemId, item.id),
          eq(itemLikes.userId, currentUserId)
        ))
        .limit(1);

      if (existing.length > 0) {
        // Update or delete
        if (existing[0].score === score) {
          // Delete if same score clicked again (toggle off)
          await db
            .delete(itemLikes)
            .where(and(
              eq(itemLikes.itemId, item.id),
              eq(itemLikes.userId, currentUserId)
            ));
          liked = null;
        } else {
          // Update
          await db
            .update(itemLikes)
            .set({ score, createdAt: new Date() })
            .where(and(
              eq(itemLikes.itemId, item.id),
              eq(itemLikes.userId, currentUserId)
            ));
          liked = score;
        }
      } else {
        // Insert
        await db.insert(itemLikes).values({
          userId: currentUserId,
          itemId: item.id,
          score,
          createdAt: new Date(),
        } as any);
        liked = score;
      }
    } catch (err) {
      logger.error('Failed to toggle like:', err);
    } finally {
      loading = false;
    }
  }

  function excerpt(text: string | null | undefined, length: number = 150): string {
    if (!text) return '';
    if (text.length <= length) return text;
    // Try to break at a word boundary
    const truncated = text.substring(0, length);
    const lastSpace = truncated.lastIndexOf(' ');
    return (lastSpace > length * 0.8 ? truncated.substring(0, lastSpace) : truncated) + '...';
  }

  function formatDate(date: Date): string {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  function getSourceIcon(): string {
    switch (item.sourceType) {
      case 'paper':
        return '📄';
      case 'newsletter':
        return '📧';
      case 'blog':
        return '✍️';
      case 'tweet':
        return '🐦';
      default:
        return '📌';
    }
  }
</script>

<div class="card paper-card">
  <div class="paper-header">
    <div class="flex items-start gap-2 mb-2">
      <div class="flex-1 min-w-0">
        <h3 class="paper-title">{item.title}</h3>
      </div>
      <div class="flex items-center gap-1.5 flex-shrink-0">
        {#if item.rawMetadata?.categories}
          <span class="paper-category-badge">{item.rawMetadata.categories[0]}</span>
        {/if}
        <span class="paper-source-type">
          {item.sourceType === 'paper' ? 'Paper'
            : item.sourceType === 'tweet' ? 'Social'
            : item.sourceType === 'blog' ? 'Blog'
            : item.sourceType === 'newsletter' ? 'Newsletter'
            : 'Other'}
        </span>
      </div>
    </div>
    <p class="paper-source">{getSourceIcon()} {sourceName}</p>
  </div>

  {#if item.summary}
    <div class="paper-content">
      <p class="paper-abstract">{excerpt(item.summary, 150)}</p>
    </div>
  {/if}

  <div class="paper-footer">
    <div class="flex items-center justify-between gap-2 flex-col lg:flex-row">
      <span class="paper-date">{formatDate(item.publishedAt)}</span>

      <div class="flex gap-1.5">
        <button
          class="btn-icon {liked === 1 ? 'btn-liked' : ''}"
          on:click={() => toggleLike(1)}
          disabled={loading}
          title="Like"
        >
          👍
        </button>
        <button
          class="btn-icon {liked === -1 ? 'btn-disliked' : ''}"
          on:click={() => toggleLike(-1)}
          disabled={loading}
          title="Dislike"
        >
          👎
        </button>
        <button
          class="btn-primary"
          on:click={() => window.open(item.url, '_blank')}
        >
          Open
        </button>
      </div>
    </div>
  </div>
</div>

<style>
  :global(.paper-card) {
    min-height: auto;
    height: fit-content;
    padding: 0.875rem;
    background: rgb(30, 41, 59);
    border: 1px solid rgb(51, 65, 85);
    border-radius: 0.375rem;
    transition: all 0.2s;
  }

  :global(.paper-card:hover) {
    border-color: rgb(71, 85, 105);
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  }

  :global(.paper-header) {
    margin-bottom: 0.5rem;
  }

  :global(.paper-title) {
    font-size: 0.9375rem;
    font-weight: 600;
    line-height: 1.4;
    margin: 0;
    color: rgb(241, 245, 249);
  }

  :global(.paper-source) {
    font-size: 0.8125rem;
    color: rgb(148, 163, 184);
    margin: 0;
  }

  :global(.paper-category-badge) {
    font-size: 0.65rem;
    background-color: rgb(71, 85, 105);
    padding: 0.15rem 0.4rem;
    border-radius: 0.25rem;
    color: rgb(203, 213, 225);
    white-space: nowrap;
    font-weight: 500;
    flex-shrink: 0;
    display: inline-block;
  }

  :global(.paper-source-type) {
    font-size: 0.65rem;
    background-color: rgba(15, 23, 42, 0.6);
    padding: 0.15rem 0.4rem;
    border-radius: 0.25rem;
    color: rgb(203, 213, 225);
    font-weight: 600;
    white-space: nowrap;
    flex-shrink: 0;
    display: inline-block;
  }

  :global(.paper-content) {
    margin-bottom: 0;
    flex-shrink: 0;
    height: auto;
  }

  :global(.paper-abstract) {
    font-size: 0.8125rem;
    line-height: 1.5;
    margin: 0;
    color: rgb(203, 213, 225);
  }

  :global(.paper-footer) {
    margin-top: 0.5rem;
    padding-top: 0.5rem;
    border-top: 1px solid rgb(51, 65, 85);
  }

  :global(.paper-date) {
    font-size: 0.6875rem;
    color: rgb(148, 163, 184);
    font-weight: 500;
  }

  :global(.btn-icon) {
    background-color: rgb(51, 65, 85);
    color: rgb(226, 232, 240);
    border: 1px solid rgb(71, 85, 105);
    border-radius: 0.25rem;
    padding: 0.375rem 0.625rem;
    cursor: pointer;
    font-size: 0.9375rem;
    transition: all 0.2s;
    line-height: 1;
  }

  :global(.btn-icon:hover:not(:disabled)) {
    background-color: rgb(71, 85, 105);
    border-color: rgb(100, 116, 139);
  }

  :global(.btn-icon:disabled) {
    opacity: 0.5;
    cursor: not-allowed;
  }

  :global(.btn-liked) {
    background-color: rgb(5, 150, 105);
    border-color: rgb(5, 150, 105);
  }

  :global(.btn-disliked) {
    background-color: rgb(220, 38, 38);
    border-color: rgb(220, 38, 38);
  }

  :global(.btn-primary) {
    background-color: rgb(59, 130, 246);
    color: white;
    border: none;
    border-radius: 0.25rem;
    padding: 0.375rem 0.75rem;
    cursor: pointer;
    font-size: 0.8125rem;
    font-weight: 500;
    transition: all 0.2s;
  }

  :global(.btn-primary:hover) {
    background-color: rgb(37, 99, 235);
  }
</style>

// web/src/components/ItemCard.tsx
import { useState, memo } from 'react';
import { Box, Flex, Text, Button, Badge } from '@chakra-ui/react';
import { getDb } from '@/lib/db';
import { itemLikes } from '@/lib/schema';
import { eq, and } from 'drizzle-orm';
import { useUser } from '@/contexts/UserContext';
import { formatDate, excerpt } from '@/utils/formatting';
import { logger } from '@/utils/logger';
import { ExternalLink, ThumbsUp, ThumbsDown } from 'lucide-react';
import type { Item } from '@/lib/items';

interface ItemCardProps {
  item: Item;
  sourceName?: string;
  initialLiked?: number | null;
  onLikeChange?: () => void;
}

function getSourceIcon(sourceType: string): string {
  switch (sourceType) {
    case 'paper':
      return '📄';
    case 'newsletter':
      return '📧';
    case 'blog':
      return '✍️';
    case 'tweet':
      return '🐦';
    default:
      return '📌';
  }
}

function getSourceTypeLabel(sourceType: string): string {
  switch (sourceType) {
    case 'paper':
      return 'Paper';
    case 'tweet':
      return 'Social';
    case 'blog':
      return 'Blog';
    case 'newsletter':
      return 'Newsletter';
    default:
      return 'Other';
  }
}

function getSourceTypeColor(sourceType: string): string {
  switch (sourceType) {
    case 'paper':
      return 'purple';
    case 'tweet':
      return 'blue';
    case 'blog':
      return 'orange';
    case 'newsletter':
      return 'green';
    default:
      return 'gray';
  }
}

const ItemCard = memo(function ItemCard({ item, sourceName = 'Unknown', initialLiked = null, onLikeChange }: ItemCardProps) {
  const { userId } = useUser();
  const [liked, setLiked] = useState<number | null>(initialLiked);
  const [loading, setLoading] = useState(false);

  async function toggleLike(score: number) {
    if (loading) return;
    setLoading(true);

    try {
      const db = await getDb();

      // Check if like exists
      const existing = await db
        .select()
        .from(itemLikes)
        .where(and(
          eq(itemLikes.itemId, item.id),
          eq(itemLikes.userId, userId)
        ))
        .limit(1);

      if (existing.length > 0) {
        // Update or delete
        if (existing[0].score === score) {
          // Delete if same score clicked again (toggle off)
          await db
            .delete(itemLikes)
            .where(and(
              eq(itemLikes.itemId, item.id),
              eq(itemLikes.userId, userId)
            ));
          setLiked(null);
        } else {
          // Update
          await db
            .update(itemLikes)
            .set({ score, createdAt: new Date() })
            .where(and(
              eq(itemLikes.itemId, item.id),
              eq(itemLikes.userId, userId)
            ));
          setLiked(score);
        }
      } else {
        // Insert
        await db.insert(itemLikes).values({
          userId,
          itemId: item.id,
          score,
          createdAt: new Date(),
        } as any);
        setLiked(score);
      }

      // Notify parent to refresh likes
      if (onLikeChange) {
        onLikeChange();
      }
    } catch (err) {
      logger.error('Failed to toggle like:', err);
    } finally {
      setLoading(false);
    }
  }

  const categories = item.rawMetadata?.categories;
  const sourceTypeColor = getSourceTypeColor(item.sourceType);

  return (
    <Box
      bg="gray.800"
      borderWidth="1px"
      borderColor="gray.700"
      rounded="lg"
      overflow="hidden"
      transition="all 0.2s"
      _hover={{
        borderColor: 'gray.600',
        shadow: 'lg',
        transform: 'translateY(-2px)',
      }}
      h="full"
      display="flex"
      flexDirection="column"
    >
      {/* Header */}
      <Box p={4} borderBottomWidth="1px" borderColor="gray.700">
        <Flex align="flex-start" gap={3} mb={2}>
          <Text
            fontSize="md"
            fontWeight="bold"
            lineHeight="1.4"
            color="gray.50"
            flex={1}
            minW={0}
          >
            {item.title}
          </Text>
        </Flex>

        <Flex align="center" gap={2} wrap="wrap">
          <Badge
            colorScheme={sourceTypeColor}
            variant="subtle"
            fontSize="xs"
            px={2}
            py={0.5}
            rounded="md"
            fontWeight="semibold"
          >
            {getSourceIcon(item.sourceType)} {getSourceTypeLabel(item.sourceType)}
          </Badge>
          {categories && categories.length > 0 && (
            <Badge
              fontSize="xs"
              px={2}
              py={0.5}
              rounded="md"
              bg="gray.700"
              color="gray.300"
              borderWidth="1px"
              borderColor="gray.600"
            >
              {categories[0]}
            </Badge>
          )}
          <Text fontSize="xs" color="gray.500" ml="auto">
            {formatDate(item.publishedAt)}
          </Text>
        </Flex>
      </Box>

      {/* Body */}
      <Box p={4} flex={1}>
        <Text fontSize="xs" color="gray.500" mb={2} fontWeight="medium">
          {sourceName}
        </Text>

        {/* Summary */}
        {item.summary && (
          <Text fontSize="sm" lineHeight="1.6" color="gray.300" mb={3}>
            {excerpt(item.summary, 150)}
          </Text>
        )}

        {/* Topics */}
        {item.topics && item.topics.length > 0 && (
          <Flex gap={1.5} flexWrap="wrap">
            {item.topics.map(topic => (
              <Badge
                key={topic}
                colorScheme="purple"
                variant="subtle"
                fontSize="xs"
                px={2}
                py={0.5}
                rounded="md"
              >
                {topic}
              </Badge>
            ))}
          </Flex>
        )}
      </Box>

      {/* Footer */}
      <Box p={4} pt={3} borderTopWidth="1px" borderColor="gray.700" bg="gray.850">
        <Flex justify="space-between" align="center" gap={2}>
          <Flex gap={1.5}>
            <Button
              size="sm"
              onClick={() => toggleLike(1)}
              isLoading={loading}
              minW="60px"
              title={liked === 1 ? "Remove like" : "Like this"}
              bg={liked === 1 ? 'green.600' : 'transparent'}
              color={liked === 1 ? 'white' : 'green.400'}
              borderWidth="1px"
              borderColor={liked === 1 ? 'green.600' : 'green.700'}
              _hover={{
                bg: liked === 1 ? 'green.500' : 'green.900',
                borderColor: liked === 1 ? 'green.500' : 'green.600',
              }}
            >
              <Flex gap={1.5} align="center">
                <ThumbsUp size={14} />
                <Text fontSize="xs">Like</Text>
              </Flex>
            </Button>
            <Button
              size="sm"
              onClick={() => toggleLike(-1)}
              isLoading={loading}
              minW="70px"
              title={liked === -1 ? "Remove dislike" : "Dislike this"}
              bg={liked === -1 ? 'red.600' : 'transparent'}
              color={liked === -1 ? 'white' : 'red.400'}
              borderWidth="1px"
              borderColor={liked === -1 ? 'red.600' : 'red.700'}
              _hover={{
                bg: liked === -1 ? 'red.500' : 'red.900',
                borderColor: liked === -1 ? 'red.500' : 'red.600',
              }}
            >
              <Flex gap={1.5} align="center">
                <ThumbsDown size={14} />
                <Text fontSize="xs">Dislike</Text>
              </Flex>
            </Button>
          </Flex>
          <Button
            size="sm"
            onClick={() => window.open(item.url, '_blank')}
            title="Open in new tab"
            bg="blue.600"
            color="white"
            _hover={{ bg: 'blue.500' }}
          >
            <Flex gap={1.5} align="center">
              <Text fontSize="xs">Open</Text>
              <ExternalLink size={14} />
            </Flex>
          </Button>
        </Flex>
      </Box>
    </Box>
  );
});

export default ItemCard;
